package simpleaudioplayer;

import java.awt.BorderLayout;
import java.awt.Component;
import java.net.MalformedURLException;
import java.net.URL;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.Player;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

public class Video extends javax.swing.JFrame {

    public Video(URL mediauUrl) {
        initComponents();
        
        setLayout(new BorderLayout());
 
        try {

        Player mediaPlayer=Manager.createRealizedPlayer(new MediaLocator(mediauUrl));

        Component video=mediaPlayer.getVisualComponent();

        Component control=mediaPlayer.getControlPanelComponent();

        if (video!=null) {

        add(video, BorderLayout.CENTER);          // place the video component in the panel

        }

        add(control, BorderLayout.SOUTH);            // place the control in  panel

        mediaPlayer.start();

        } catch (Exception e) {

        }
    }

    private Video() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
            JFileChooser fileChooser = new JFileChooser();

            fileChooser.showOpenDialog(null);

            URL mediaUrl=null;

            try {

                mediaUrl = fileChooser.getSelectedFile().toURI().toURL();

            } catch (MalformedURLException ex) {

                System.out.println(ex);

            }

            JFrame mediaTest = new JFrame( "Movie Player" );

            mediaTest.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );

            Video mediaPanel = new Video( mediaUrl );

            mediaTest.add( mediaPanel );
            mediaTest.setSize( 640, 360); // set the size of the player

            mediaTest.setSize( 640, 360); // set the size of the player

            mediaTest.setLocationRelativeTo(null);

            mediaTest.setVisible( true );
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Video().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
